// This file is auto-generated by ./bin/buildMain.js

const ADT = {
  Err: require('./ADT/Err'),
  Just: require('./ADT/Just'),
  List: require('./ADT/List'),
  Nothing: require('./ADT/Nothing'),
  Ok: require('./ADT/Ok'),
  Pair: require('./ADT/Pair')
}

const Boolean = {
  conditionalCheck: require('./Boolean/conditionalCheck'),
  failsModelCheck: require('./Boolean/failsModelCheck'),
  hasNoDuplicates: require('./Boolean/hasNoDuplicates'),
  isArray: require('./Boolean/isArray'),
  isEmpty: require('./Boolean/isEmpty'),
  isEqual: require('./Boolean/isEqual'),
  isEquivalent: require('./Boolean/isEquivalent'),
  isErr: require('./Boolean/isErr'),
  isFunction: require('./Boolean/isFunction'),
  isGT: require('./Boolean/isGT'),
  isGTCustom: require('./Boolean/isGTCustom'),
  isGTE: require('./Boolean/isGTE'),
  isGeneratorFunction: require('./Boolean/isGeneratorFunction'),
  isLT: require('./Boolean/isLT'),
  isLTE: require('./Boolean/isLTE'),
  isNil: require('./Boolean/isNil'),
  isNotEmpty: require('./Boolean/isNotEmpty'),
  isNull: require('./Boolean/isNull'),
  isNumber: require('./Boolean/isNumber'),
  isObject: require('./Boolean/isObject'),
  isOfKind: require('./Boolean/isOfKind'),
  isOk: require('./Boolean/isOk'),
  isResult: require('./Boolean/isResult'),
  isString: require('./Boolean/isString'),
  isUndefined: require('./Boolean/isUndefined'),
  neighborsPass: require('./Boolean/neighborsPass'),
  passesModelCheck: require('./Boolean/passesModelCheck'),
  passesObjKeyCheck: require('./Boolean/passesObjKeyCheck'),
  passesObjValCheck: require('./Boolean/passesObjValCheck'),
  satisfiesBetweenBounds: require('./Boolean/satisfiesBetweenBounds'),
  satisfiesLowerBound: require('./Boolean/satisfiesLowerBound'),
  satisfiesUpperBound: require('./Boolean/satisfiesUpperBound')
}

const Conversion = {
  boolsToInt: require('./Conversion/boolsToInt'),
  escapeForRegExp: require('./Conversion/escapeForRegExp'),
  format: require('./Conversion/format'),
  fracStrToNum: require('./Conversion/fracStrToNum'),
  fracToNum: require('./Conversion/fracToNum'),
  fraction: require('./Conversion/fraction'),
  fromPairs: require('./Conversion/fromPairs'),
  objFromEntries: require('./Conversion/objFromEntries'),
  objToEntries: require('./Conversion/objToEntries'),
  resultToPOJO: require('./Conversion/resultToPOJO'),
  resultUnwrap: require('./Conversion/resultUnwrap'),
  toPairs: require('./Conversion/toPairs'),
  wrapNonArray: require('./Conversion/wrapNonArray')
}

const Datetime = {
  RE_UTC_TIMESTAMP: require('./Datetime/RE_UTC_TIMESTAMP'),
  addSeconds: require('./Datetime/addSeconds'),
  estRemainingDur: require('./Datetime/estRemainingDur'),
  estTotalDur: require('./Datetime/estTotalDur'),
  etaDurStr: require('./Datetime/etaDurStr'),
  etaTimeStr: require('./Datetime/etaTimeStr'),
  now: require('./Datetime/now'),
  parseUTCStr: require('./Datetime/parseUTCStr'),
  sysLocale: require('./Datetime/sysLocale'),
  sysTimezone: require('./Datetime/sysTimezone'),
  toLocaleString: require('./Datetime/toLocaleString'),
  utcStrToDate: require('./Datetime/utcStrToDate')
}

const Functional = {
  F: require('./Functional/F'),
  T: require('./Functional/T'),
  _swapFields: require('./Functional/_swapFields'),
  addPreprocessFn2: require('./Functional/addPreprocessFn2'),
  all: require('./Functional/all'),
  assocComputed: require('./Functional/assocComputed'),
  chain: require('./Functional/chain'),
  clone: require('./Functional/clone'),
  cloneAssoc: require('./Functional/cloneAssoc'),
  cmpIndexable: require('./Functional/cmpIndexable'),
  comparator: require('./Functional/comparator'),
  compare: require('./Functional/compare'),
  compareFracStr: require('./Functional/compareFracStr'),
  constant: require('./Functional/constant'),
  curry: require('./Functional/curry'),
  either: require('./Functional/either'),
  filter: require('./Functional/filter'),
  filterKV: require('./Functional/filterKV'),
  find: require('./Functional/find'),
  findBest: require('./Functional/findBest'),
  flatten: require('./Functional/flatten'),
  flip: require('./Functional/flip'),
  getPath: require('./Functional/getPath'),
  getProp: require('./Functional/getProp'),
  groupBy: require('./Functional/groupBy'),
  head: require('./Functional/head'),
  identity: require('./Functional/identity'),
  length: require('./Functional/length'),
  lensProp: require('./Functional/lensProp'),
  liftA2: require('./Functional/liftA2'),
  liftA2Join: require('./Functional/liftA2Join'),
  liftA3: require('./Functional/liftA3'),
  liftA3Join: require('./Functional/liftA3Join'),
  listPush: require('./Functional/listPush'),
  map: require('./Functional/map'),
  mapObjIndexed: require('./Functional/mapObjIndexed'),
  mapWithIndex: require('./Functional/mapWithIndex'),
  max: require('./Functional/max'),
  mergeDeepLeft: require('./Functional/mergeDeepLeft'),
  mergeDeepRight: require('./Functional/mergeDeepRight'),
  mergeRight: require('./Functional/mergeRight'),
  mergeWith: require('./Functional/mergeWith'),
  negate: require('./Functional/negate'),
  omit: require('./Functional/omit'),
  over: require('./Functional/over'),
  permuterGenFn: require('./Functional/permuterGenFn'),
  pick: require('./Functional/pick'),
  pickBy: require('./Functional/pickBy'),
  pipe: require('./Functional/pipe'),
  pluck: require('./Functional/pluck'),
  reduce: require('./Functional/reduce'),
  reverse: require('./Functional/reverse'),
  setArity: require('./Functional/setArity'),
  sortBy: require('./Functional/sortBy'),
  swapFields: require('./Functional/swapFields'),
  tap: require('./Functional/tap'),
  truthTable: require('./Functional/truthTable'),
  uniq: require('./Functional/uniq'),
  view: require('./Functional/view'),
  when: require('./Functional/when')
}

const Math = {
  absRelChange: require('./Math/absRelChange'),
  growth: require('./Math/growth'),
  relChangeToMult: require('./Math/relChangeToMult'),
  roundEven: require('./Math/roundEven'),
  roundToMultiple: require('./Math/roundToMultiple'),
  roundToPrecision: require('./Math/roundToPrecision'),
  snapRelative: require('./Math/snapRelative')
}

const Misc = {
  callerFuncName: require('./Misc/callerFuncName'),
  currentFuncName: require('./Misc/currentFuncName'),
  dumpJSON: require('./Misc/dumpJSON'),
  pause: require('./Misc/pause'),
  throwError: require('./Misc/throwError')
}

const Model = {
  AnyModel: require('./Model/AnyModel'),
  DatetimeModel: require('./Model/DatetimeModel'),
  EmptyArrModel: require('./Model/EmptyArrModel'),
  FractionStrModel: require('./Model/FractionStrModel'),
  FunctionModel: require('./Model/FunctionModel'),
  IntegerModel: require('./Model/IntegerModel'),
  NonBlankStrModel: require('./Model/NonBlankStrModel'),
  NonEmptyArrModel: require('./Model/NonEmptyArrModel'),
  NonNegativeIntModel: require('./Model/NonNegativeIntModel'),
  NonNegativeNumModel: require('./Model/NonNegativeNumModel'),
  NumZeroToOneModel: require('./Model/NumZeroToOneModel'),
  NumZeroToOneXModel: require('./Model/NumZeroToOneXModel'),
  NumberModel: require('./Model/NumberModel'),
  ObjectModel: require('./Model/ObjectModel'),
  PositiveFracStrModel: require('./Model/PositiveFracStrModel'),
  PositiveIntModel: require('./Model/PositiveIntModel'),
  PositiveNumModel: require('./Model/PositiveNumModel'),
  StringModel: require('./Model/StringModel'),
  UTCStrModel: require('./Model/UTCStrModel')
}

const ModelAssertion = {
  _boundBetweenErrMsg: require('./ModelAssertion/_boundBetweenErrMsg'),
  _boundLowerErrMsg: require('./ModelAssertion/_boundLowerErrMsg'),
  _boundUpperErrMsg: require('./ModelAssertion/_boundUpperErrMsg'),
  _objBadKeyErrMsg: require('./ModelAssertion/_objBadKeyErrMsg'),
  _objBadValErrMsg: require('./ModelAssertion/_objBadValErrMsg'),
  assertAfterCheck: require('./ModelAssertion/assertAfterCheck'),
  assertBounded: require('./ModelAssertion/assertBounded'),
  assertBoundedBetween: require('./ModelAssertion/assertBoundedBetween'),
  assertBoundedLower: require('./ModelAssertion/assertBoundedLower'),
  assertBoundedUpper: require('./ModelAssertion/assertBoundedUpper'),
  assertEmpty: require('./ModelAssertion/assertEmpty'),
  assertMatchesRegex: require('./ModelAssertion/assertMatchesRegex'),
  assertNeighborsPass: require('./ModelAssertion/assertNeighborsPass'),
  assertNotEmpty: require('./ModelAssertion/assertNotEmpty'),
  assertNothing: require('./ModelAssertion/assertNothing'),
  assertObjKeysValid: require('./ModelAssertion/assertObjKeysValid'),
  assertObjValuesValid: require('./ModelAssertion/assertObjValuesValid'),
  assertOrdered: require('./ModelAssertion/assertOrdered'),
  assertPropMaxGTEMin: require('./ModelAssertion/assertPropMaxGTEMin'),
  assertPropRel: require('./ModelAssertion/assertPropRel'),
  assertValidUTCStr: require('./ModelAssertion/assertValidUTCStr'),
  assertionErrMsg: require('./ModelAssertion/assertionErrMsg')
}

const ModelFactory = {
  defArrModel: require('./ModelFactory/defArrModel'),
  defBasicModel: require('./ModelFactory/defBasicModel'),
  defBoundedFracStrModel: require('./ModelFactory/defBoundedFracStrModel'),
  defBoundedIntModel: require('./ModelFactory/defBoundedIntModel'),
  defBoundedNumModel: require('./ModelFactory/defBoundedNumModel'),
  defCheckedKVObjModel: require('./ModelFactory/defCheckedKVObjModel'),
  defNonEmptyArrModel: require('./ModelFactory/defNonEmptyArrModel'),
  defObjModel: require('./ModelFactory/defObjModel'),
  defRegexMatchedStrModel: require('./ModelFactory/defRegexMatchedStrModel'),
  defSealedObjModel: require('./ModelFactory/defSealedObjModel')
}

const Validation = {
  RE_RATIONAL: require('./Validation/RE_RATIONAL'),
  _throwIfNotErr: require('./Validation/_throwIfNotErr'),
  _throwIfNotResult: require('./Validation/_throwIfNotResult'),
  _typeWithOkErr: require('./Validation/_typeWithOkErr'),
  kind: require('./Validation/kind'),
  objBadKey: require('./Validation/objBadKey'),
  objBadVal: require('./Validation/objBadVal'),
  throwIfArgsBad: require('./Validation/throwIfArgsBad'),
  throwIfFalse: require('./Validation/throwIfFalse'),
  throwIfTrue: require('./Validation/throwIfTrue'),
  throwIfUndefined: require('./Validation/throwIfUndefined'),
  validatePropName: require('./Validation/validatePropName'),
  validateWithFn: require('./Validation/validateWithFn'),
  validateWithModel: require('./Validation/validateWithModel')
}

module.exports = {
  ADT,
  Boolean,
  Conversion,
  Datetime,
  Functional,
  Math,
  Misc,
  Model,
  ModelAssertion,
  ModelFactory,
  Validation
}
